# Shared defaults for all services
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

server:
  error:
    include-message: always
    include-binding-errors: always
