server:
  port: 9001

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/skillsync_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: USERNAME
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret: "skillsyncskillsyncskillsyncskillsyncskillsync12345"
    expiration-ms: 86400000
    refresh-expiration-ms: 604800000

